services:
  db:
    image: mysql:8.0
    container_name: mysql_dev
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    ports:
      - "3307:3306"
    volumes:
      - devdojo_data:/var/lib/mysql

volumes:
  devdojo_data:
